format_version: 10
pipelines:
  yaml-test-pipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-5913e5f:
        git: https://github.com/kivakin/security-user-login-db-autorize.git
        username: rhs
        shallow_clone: false
        auto_update: true
        branch: master
        encrypted_password: AES:rCEBplMUdaUtdsNsHO6P0Q==:Jkha4Ue3fNgrKPePGWAwmhwYsAkfVxn/Z1nJC9HVK8o84iOT1MSCTfCwuiV9aHJj
    stages:
    - build-stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-unit-job:
            timeout: 0
          tasks:
            - exec:
                arguments:
                - -c
                - ./gradlew -Pversion=0.0.1
                command: bash
                run_if: passed
            - exec:
                arguments:
                - clean
                - build
                command: ./gradlew
                run_if: passed
            - exec:
                arguments:
                - -c
                - java -jar build/libs/spring-security-master-0.0.1-SNAPSHOT.jar
                command: bash
                run_if: passed