spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pinocchio?currentSchema=pnc_schema
    username: pinocchio
    password: pnc12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  thymeleaf:
    cache: false